"""add_indices_atleta_nome_cpf

Revision ID: 91ba0a4a3a82
Revises: c006e8463eb4
Create Date: 2026-02-28 23:14:50.485158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ba0a4a3a82'
down_revision = 'c006e8463eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('atletas_cpf_key'), 'atletas', type_='unique')
    op.create_index(op.f('ix_atletas_cpf'), 'atletas', ['cpf'], unique=True)
    op.create_index(op.f('ix_atletas_nome'), 'atletas', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atletas_nome'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_cpf'), table_name='atletas')
    op.create_unique_constraint(op.f('atletas_cpf_key'), 'atletas', ['cpf'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
